services:
  web:
    build:
      context: .
      dockerfile: ./apps/web/Dockerfile
    ports:
      - "3000:3000"
    networks:
      - app_network
  api:
    build:
      context: .
      dockerfile: ./apps/api/Dockerfile
    ports:
      - "8000:8000"
    environment:
      - TICKER_SOURCE=Kraken
      - TICKER_SOURCE_TTL=30
      - REDIS_URL=redis:6379
    networks:
      - app_network
  redis:
    image: redis
    networks:
      - app_network

networks:
  app_network:
    external: false